find_path(FLITE_INCLUDE_DIR flite/flite.h)

if(FLITE_INCLUDE_DIR AND NOT Flite_FIND_QUIETLY)
  message(STATUS "Found flite includes: ${FLITE_INCLUDE_DIR}/flite/flite.h")
endif()

find_library(FLITE_LIBRARY NAMES flite)
if(NOT Flite_NOT_QUIETLY)
  if(FLITE_LIBRARY)
    message(STATUS "Found flite library: ${FLITE_LIBRARY}")
  else()
    message(STATUS "flite library NOT found") 
  endif()
endif()

find_library(FLITE_CMU_US_RMS_LIBRARY NAMES flite_cmu_us_rms)
if(NOT Flite_NOT_QUIETLY)
  if(FLITE_CMU_US_RMS_LIBRARY)
    message(STATUS "Found flite_cmu_us_rms library: ${FLITE_CMU_US_RMS_LIBRARY}")
  else()
    message(STATUS "flite_cmu_us_rms library NOT found") 
  endif()
endif()

find_library(FLITE_USENGLISH_LIBRARY NAMES flite_usenglish)
if(NOT Flite_NOT_QUIETLY)
  if(FLITE_USENGLISH_LIBRARY)
    message(STATUS "Found flite_usenglish library: ${FLITE_USENGLISH_LIBRARY}")
  else()
    message(STATUS "flite_usenglish library NOT found") 
  endif()
endif()

find_library(FLITE_CMULEX_LIBRARY NAMES flite_cmulex)
if(NOT Flite_NOT_QUIETLY)
  if(FLITE_CMULEX_LIBRARY)
    message(STATUS "Found flite_cmulex library: ${FLITE_CMULEX_LIBRARY}")
  else()
    message(STATUS "flite_cmulex library NOT found") 
  endif()
endif()

if(FLITE_INCLUDE_DIR AND FLITE_LIBRARY AND FLITE_CMU_US_RMS_LIBRARY AND FLITE_USENGLISH_LIBRARY AND FLITE_CMULEX_LIBRARY)
  set(FLITE_FOUND TRUE)
endif()

mark_as_advanced(FLITE_INCLUDE_DIR FLITE_LIBRARY FLITE_CMU_US_RMS FLITE_USENGLISH FLITE_CMULEX)

if(NOT FLITE_FOUND)
  if(Flite_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find flite development files")
  endif()
endif()
